// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.26.0
// source: logxconf.proto

package logx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Encode int32

const (
	Encode_plain Encode = 0
	Encode_json  Encode = 1
)

// Enum value maps for Encode.
var (
	Encode_name = map[int32]string{
		0: "plain",
		1: "json",
	}
	Encode_value = map[string]int32{
		"plain": 0,
		"json":  1,
	}
)

func (x Encode) Enum() *Encode {
	p := new(Encode)
	*p = x
	return p
}

func (x Encode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encode) Descriptor() protoreflect.EnumDescriptor {
	return file_logxconf_proto_enumTypes[0].Descriptor()
}

func (Encode) Type() protoreflect.EnumType {
	return &file_logxconf_proto_enumTypes[0]
}

func (x Encode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encode.Descriptor instead.
func (Encode) EnumDescriptor() ([]byte, []int) {
	return file_logxconf_proto_rawDescGZIP(), []int{0}
}

// protobuf 值必须对应，否则解析会报错
type LogLevel int32

const (
	LogLevel_DEBUG LogLevel = 0
	LogLevel_INFO  LogLevel = 1
	LogLevel_WARN  LogLevel = 2
	LogLevel_ERROR LogLevel = 3
	LogLevel_FATAL LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARN",
		3: "ERROR",
		4: "FATAL",
	}
	LogLevel_value = map[string]int32{
		"DEBUG": 0,
		"INFO":  1,
		"WARN":  2,
		"ERROR": 3,
		"FATAL": 4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_logxconf_proto_enumTypes[1].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_logxconf_proto_enumTypes[1]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_logxconf_proto_rawDescGZIP(), []int{1}
}

type LogxConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathDir    string   `protobuf:"bytes,1,opt,name=path_dir,json=pathDir,proto3" json:"path_dir,omitempty"`
	FileName   string   `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Encoding   Encode   `protobuf:"varint,3,opt,name=encoding,proto3,enum=logx.Encode" json:"encoding,omitempty"`
	Level      LogLevel `protobuf:"varint,4,opt,name=level,proto3,enum=logx.LogLevel" json:"level,omitempty"`
	KeepDays   int64    `protobuf:"varint,5,opt,name=keep_days,json=keepDays,proto3" json:"keep_days,omitempty"`
	MaxBackups int64    `protobuf:"varint,6,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	MaxSize    int64    `protobuf:"varint,7,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
}

func (x *LogxConf) Reset() {
	*x = LogxConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logxconf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogxConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogxConf) ProtoMessage() {}

func (x *LogxConf) ProtoReflect() protoreflect.Message {
	mi := &file_logxconf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogxConf.ProtoReflect.Descriptor instead.
func (*LogxConf) Descriptor() ([]byte, []int) {
	return file_logxconf_proto_rawDescGZIP(), []int{0}
}

func (x *LogxConf) GetPathDir() string {
	if x != nil {
		return x.PathDir
	}
	return ""
}

func (x *LogxConf) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *LogxConf) GetEncoding() Encode {
	if x != nil {
		return x.Encoding
	}
	return Encode_plain
}

func (x *LogxConf) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_DEBUG
}

func (x *LogxConf) GetKeepDays() int64 {
	if x != nil {
		return x.KeepDays
	}
	return 0
}

func (x *LogxConf) GetMaxBackups() int64 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *LogxConf) GetMaxSize() int64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

var File_logxconf_proto protoreflect.FileDescriptor

var file_logxconf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x78, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6c, 0x6f, 0x67, 0x78, 0x22, 0xeb, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x78, 0x43,
	0x6f, 0x6e, 0x66, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x64, 0x69, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x68, 0x44, 0x69, 0x72, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x08, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x6c, 0x6f, 0x67, 0x78, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x65, 0x6e, 0x63,
	0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6c, 0x6f, 0x67, 0x78, 0x2e, 0x4c, 0x6f, 0x67, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x6b,
	0x65, 0x65, 0x70, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x6b, 0x65, 0x65, 0x70, 0x44, 0x61, 0x79, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f,
	0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6d,
	0x61, 0x78, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6d, 0x61, 0x78,
	0x53, 0x69, 0x7a, 0x65, 0x2a, 0x1d, 0x0a, 0x06, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x09,
	0x0a, 0x05, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x6a, 0x73, 0x6f,
	0x6e, 0x10, 0x01, 0x2a, 0x3f, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x09, 0x0a, 0x05, 0x44, 0x45, 0x42, 0x55, 0x47, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x4e,
	0x46, 0x4f, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x52, 0x4e, 0x10, 0x02, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x41, 0x54,
	0x41, 0x4c, 0x10, 0x04, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x61, 0x6f, 0x67, 0x6f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x6c, 0x6f, 0x67, 0x78, 0x3b, 0x6c, 0x6f, 0x67, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_logxconf_proto_rawDescOnce sync.Once
	file_logxconf_proto_rawDescData = file_logxconf_proto_rawDesc
)

func file_logxconf_proto_rawDescGZIP() []byte {
	file_logxconf_proto_rawDescOnce.Do(func() {
		file_logxconf_proto_rawDescData = protoimpl.X.CompressGZIP(file_logxconf_proto_rawDescData)
	})
	return file_logxconf_proto_rawDescData
}

var file_logxconf_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_logxconf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_logxconf_proto_goTypes = []interface{}{
	(Encode)(0),      // 0: logx.Encode
	(LogLevel)(0),    // 1: logx.LogLevel
	(*LogxConf)(nil), // 2: logx.LogxConf
}
var file_logxconf_proto_depIdxs = []int32{
	0, // 0: logx.LogxConf.encoding:type_name -> logx.Encode
	1, // 1: logx.LogxConf.level:type_name -> logx.LogLevel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_logxconf_proto_init() }
func file_logxconf_proto_init() {
	if File_logxconf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logxconf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogxConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logxconf_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logxconf_proto_goTypes,
		DependencyIndexes: file_logxconf_proto_depIdxs,
		EnumInfos:         file_logxconf_proto_enumTypes,
		MessageInfos:      file_logxconf_proto_msgTypes,
	}.Build()
	File_logxconf_proto = out.File
	file_logxconf_proto_rawDesc = nil
	file_logxconf_proto_goTypes = nil
	file_logxconf_proto_depIdxs = nil
}
